### ISSUE TITLE
recover date before deployment date

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#56]
**Note: this table was updated, integrated the comments of the discussion below**

The following receivers have a `recover_date_time` that falls before `deploy_date_time`. This is odd. 
Can provide the correct dates and times here?

   receiver |   recover_date_time |    deploy_date_time | id_pk |          projectname
 -----------|---------------------|---------------------|-------|---------------------
VR2W-124060 | 2016-02-11 00:00:00 | 2016-10-10 00:00:00 |  2944 |         Albertkanaal

**Comment by jreubens** [comment]
for receiver 129569, this was a mistake in YEAR. Should be 2018 instead of 2019. this has been adapted.
For the receiver of Albertkanaal @IPauwels @PieterjanVerhelst  should answer

**Comment by PieterjanVerhelst** [comment]
For receiver 'VR2W-124060', the deploy and recover dates do not match the data range of the receiver log files. I tried to clear it out, but to be complete, I would need the file of deployment '3' in the table beneath. That is file 'VR2W_124060_20170612_1.csv'.

| order number| receiver    | deploy     | recover    | data date range         |
|----------------|-------------|------------|------------|-------------------------|
| 1 | VR2W-124060 | 2015-09-28 | 2016-10-10 | 2016-04-13 - 2016-04-21 | 
| 2 | VR2W-124060 | 2016-10-10 | 2016-02-11 | 2015-10-03 - 2015-12-01 | 
| 3 | VR2W-124060 | 2016-02-11 | 2017-06-12 | ? | 

So the order should be:

| order number| receiver    | deploy     | recover    | data date range         |
|----------------|-------------|------------|------------|-------------------------|
| 2 | VR2W-124060 | 2016-10-10 | 2016-02-11 | 2015-10-03 - 2015-12-01 | 
| 1 | VR2W-124060 | 2015-09-28 | 2016-10-10 | 2016-04-13 - 2016-04-21 | 
| 3 | VR2W-124060 | 2016-02-11 | 2017-06-12 | ? | 

Obviously, the deploy and recover dates should be changed accordingly. Suggestion:

| order number| receiver    | deploy     | recover    | data date range         |
|----------------|-------------|------------|------------|-------------------------|
| 2 (2944) | VR2W-124060 | 2016-10-10 -> **2015-10-03** | 2016-02-11 | 2015-10-03 - 2015-12-01 | 
| 1 (1570) | VR2W-124060 | 2015-09-28 -> **2016-02-11** | 2016-10-10 | 2016-04-13 - 2016-04-21 | 
| 3 (2445) | VR2W-124060 | 2016-02-11 -> **2016-10-10** | 2017-06-12 | ? | 

Note that the deploy date of the last line is an assumption, since I cannot check the date of the first detection, because I don't have the file.

@IPauwels, can you check this?

**Comment by peterdesmet** [comment]
This has been resolved in the database as suggested by Pieterjan. The number of detections returned is unchanged :+1:
